"use client";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { AppDialog } from "./AppDialog";
import { suggestWarrantyCriterion } from "@/lib/warranty-selection";
type Criterion={id:string;category:string;workName:string;warrantyYears:number;bondRate:number|null;sourceName:string;sourcePage:string;sourceExcerpt:string};
type Inspection={id:number;sequence:number;scheduledDate:string;status:string;inspectedAt:string|null};
export function Phase8WarrantyWorkspace({contractId,currentStage,projectName,constructionType,defaultStartDate,criteria,warranty,inspections}:{contractId:string;currentStage:string;projectName:string;constructionType:string;defaultStartDate:string|null;criteria:Criterion[];warranty:Record<string,unknown>|null;inspections:Inspection[]}){
 const router=useRouter(); const suggested=useMemo(()=>suggestWarrantyCriterion(criteria,projectName,constructionType),[criteria,projectName,constructionType]);
 const storedCriterionId=String(warranty?.criterionId??""); const replaceLegacyStructuralMismatch=storedCriterionId==="W03"&&suggested?.id==="W06";
 const [criterionId,setCriterionId]=useState(String(replaceLegacyStructuralMismatch?suggested?.id:(storedCriterionId||suggested?.id||criteria[0]?.id||""))); const [startDate,setStartDate]=useState(String(warranty?.warrantyStartDate??defaultStartDate??"")); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [confirmOpen,setConfirmOpen]=useState(false); const selected=criteria.find(c=>c.id===criterionId); const canConfirm=currentStage==="FINISHED"||!!warranty;
 async function act(body:Record<string,unknown>,key:string){setBusy(key);setError("");try{const response=await fetch(`/api/contracts/${contractId}/warranty`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"저장하지 못했습니다.");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"저장하지 못했습니다.");}finally{setBusy("");}}
 function requestConfirm(){if(!selected)return setError("하자기간 기준을 선택해 주세요.");setConfirmOpen(true);}
 function confirm(){setConfirmOpen(false);void act({action:"confirm",criterionId,startDate},"confirm");}
 return <><AppDialog open={confirmOpen} title="이 하자기간 기준으로 확정하시겠습니까?" confirmLabel="기준 확정" busy={busy==="confirm"} onCancel={()=>setConfirmOpen(false)} onConfirm={confirm}>{selected&&<><p><strong>{selected.workName}</strong></p><p>하자담보기간 {selected.warrantyYears}년 · 보증금률 {selected.bondRate==null?"[확인 필요]":`${selected.bondRate*100}%`} · 시작일 {startDate}</p></>}</AppDialog><section className="phase7-head"><div><span className="section-kicker">Phase 8 · 하자관리</span><h2>하자기간 확인과 대장 생성</h2><p>자료의 공종별 기준을 확인한 뒤 담당자가 확정해야 일정과 대장이 만들어집니다.</p></div><span className="human-check-badge">담당자 확정 필수</span></section>{error&&<div className="document-message error" role="alert">{error}</div>}
 <section className="warranty-layout"><article className="info-card"><div className="card-title"><div><span className="section-kicker">기준 검색</span><h2>공종별 하자담보기간</h2></div></div>
 <label className="warranty-field">적용 공종<select value={criterionId} onChange={e=>setCriterionId(e.target.value)}>{criteria.map(c=><option key={c.id} value={c.id}>[{c.category}] {c.workName} · {c.warrantyYears}년</option>)}</select></label>
 <label className="warranty-field">하자담보 시작일<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label>
 {selected&&<div className="warranty-evidence"><strong>{selected.warrantyYears}년 · 보증금률 {selected.bondRate==null?"[확인 필요]":`${selected.bondRate*100}%`}</strong><p>{selected.sourceExcerpt}</p><small>근거: {selected.sourceName} {selected.sourcePage}</small></div>}
 {replaceLegacyStructuralMismatch&&<div className="document-message warning">저장된 주요 구조부 기준 대신 현재 공사명에 맞는 실내의장·마감공사 기준을 선택했습니다. 아래 기준으로 다시 확정해 주세요.</div>}
 {!canConfirm&&<div className="document-message warning">적용 공종과 시작일은 미리 입력할 수 있습니다. 최종 확정은 검사검수·대금지급을 거쳐 공사완료 처리한 후 가능합니다.</div>}
 <button className="primary-action" type="button" disabled={!canConfirm||!startDate||!!busy} onClick={requestConfirm}>{busy==="confirm"?"확정 중…":warranty?"하자기간 다시 확정":"이 기준으로 확정"}</button><small className="confirmation-note">공사종류 “{constructionType}”만으로 자동 확정하지 않습니다. 실제 공종과 날짜를 확인해 주세요.</small></article>
 <article className="info-card"><div className="card-title"><div><span className="section-kicker">확정 결과</span><h2>하자검사 일정</h2></div></div>{!warranty?<div className="empty-state"><strong>아직 확정되지 않았습니다.</strong><p>왼쪽 기준과 시작일을 확인해 주세요.</p></div>:<><dl className="info-list"><div><dt>하자담보 시작</dt><dd>{String(warranty.warrantyStartDate)}</dd></div><div><dt>하자담보 종료</dt><dd>{String(warranty.warrantyEndDate)}</dd></div></dl><ol className="warranty-schedule">{inspections.map(item=><li key={item.id} className={item.status==="COMPLETED"?"done":""}><div><strong>{item.sequence}차 정기 하자검사</strong><small>{item.scheduledDate}{item.inspectedAt?` · ${item.inspectedAt.slice(0,10)} 완료`:""}</small></div>{item.status!=="COMPLETED"&&<button type="button" disabled={!!busy} onClick={()=>act({action:"complete-inspection",inspectionId:item.id},`i-${item.id}`)}>{busy===`i-${item.id}`?"저장 중…":"검사 완료"}</button>}</li>)}</ol><div className="ledger-actions"><a href={`/api/contracts/${contractId}/ledger/construction`}>공사대장 XLSM 다운로드</a><a href={`/api/contracts/${contractId}/ledger/warranty`}>하자대장 XLSM 다운로드</a></div></>}</article></section></>;
}
